# Generated by Django 5.0.1 on 2024-02-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jewellaryapp', '0003_staff_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staff_table',
            new_name='staff_tableinfo',
        ),
    ]
