# Generated by Django 5.0.1 on 2024-02-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jewellaryapp', '0004_rename_staff_table_staff_tableinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('itemimage', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
