# Generated by Django 5.0.1 on 2024-02-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jewellaryapp', '0005_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('itemimage', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.IntegerField()),
                ('material', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='add',
        ),
    ]
