# Generated by Django 5.0.1 on 2024-02-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jewellaryapp', '0007_staff_regsinfo_delete_staff_tableinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartetl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('coverimage', models.CharField(max_length=10)),
                ('itemname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
