# Generated by Django 5.0.1 on 2024-02-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jewellaryapp', '0008_cartetl'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_regsinfo',
            name='verfiystatus',
            field=models.BooleanField(default=False),
        ),
    ]
